- name: setting list
  hosts: server2
  tasks:
    - name: installing packages
      dnf:
        name:
          - chrony
          - nfs-utils
          - vim
          - tree
        state: present
